# the limit inside a window
limit = 300

# Window time in seconds.
window_time = 300

# The maximum number of unique ip addresses for one user inside a window
ip_addr_limit = 5

host = "0.0.0.0"

port = "8000"
